<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GcodeViewer</RootNamespace>
    <AssemblyName>GcodeViewer</AssemblyName>
    <Version>1.0.0</Version>
    <ApplicationDefaultFont>Microsoft YaHei UI, 9pt</ApplicationDefaultFont>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite" Version="2.6.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.59" />
  </ItemGroup>

</Project>
