using System.Drawing.Drawing2D;
using System.Text;
using GcodeViewer.Models;
using GcodeViewer.Services;
namespace GcodeViewer.Forms;

public partial class CfsGenerateForm : Form
{
    private Bitmap? _image;
    private Bitmap? _pathComparisonImage;
    private List<List<Point2D>> _paths = new();
    private string _gcode = "";
    private CfsResult? _result;
    private string _imageFileName = "";
    public CfsGenerateForm()
    {
        InitializeComponent();
        _chkPlot.CheckedChanged += (_, _) =>
        {
            if (_image != null && _paths.Count > 0) ShowPathComparison();
        };
    }
    private void BtnImport_Click(object? s, EventArgs e)
    {
        using var d = new OpenFileDialog { Filter = "图片文件|*.png;*.jpg;*.jpeg;*.bmp;*.tiff|所有文件|*.*" };
        if (d.ShowDialog(this) != DialogResult.OK)
            return;
        _picture.Image = null;
        _pathComparisonImage?.Dispose();
        _pathComparisonImage = null;
        _image?.Dispose();
        _image = new Bitmap(d.FileName);
        _imageFileName = d.FileName;
        _picture.Image = _image;
        _picture.Visible = true;
        _lblImage.Text = $"{Path.GetFileName(d.FileName)} " +
            $"({_image.Width}×{_image.Height})"; _lblStatus.Text = "图片已导入：生成时将提取实际前景轮廓";
    }
    private void BtnGenerate_Click(object? s, EventArgs e)
    {
        if (_image == null)
        { MessageBox.Show(this, "请先导入 wolf.png 或其他图片。", "提示"); return; }
        try
        {
            var o = ReadOptions();
            var sw = System.Diagnostics.Stopwatch.StartNew();
            _result = new CfsNativeAlgorithm().Generate(_image, o);
            _paths = _result.Paths;
            if (_paths.Count == 0)
                throw new InvalidOperationException("没有生成有效路径，请检查图像前景、线间距和边界偏移参数。");
            _gcode = _chkGenerateGcode.Checked ? BuildGCode(_paths, o.Layers, o.LayerHeightMm) : "";
            _txtGCode.Text = _gcode;
            _btnSave.Enabled = !string.IsNullOrWhiteSpace(_gcode);
            sw.Stop();
            _lblStatus.Text = $"{o.SpiralType}：多边形 {_result.PolygonCount} 个，" +
                $"输入轮廓 {_result.ContourCount} 个，" +
                $"等距轮廓 {_result.IsoContourCount} 个，" +
                $"路径 {_paths.Count} 条，" +
                $"点数 {_paths.Sum(p => p.Count)}，" +
                $"前景像素 {_result.ForegroundPixels}，" +
                $"尺寸 {_result.WidthMm:F1}×{_result.HeightMm:F1} mm，" +
                $"耗时 {sw.ElapsedMilliseconds} ms";
            ShowPathComparison();
        }
        catch (Exception ex) { MessageBox.Show(this, ex.Message, "生成失败", MessageBoxButtons.OK, MessageBoxIcon.Error); }
    }

    private CfsOptions ReadOptions() => new()
    {
        SpiralType = _cmbSpiralType.SelectedIndex == 0 ? "spiral" :
            _cmbSpiralType.SelectedIndex == 1 ? "fermat" : "connected_fermat",
        PixelSizeMm = (double)_nudPixelSize.Value,
        ScaleFactor = (double)_nudScaleFactor.Value,
        SpacingMm = (double)_nudSpacing.Value,
        PointSpacingMm = (double)_nudPointSpacing.Value,
        SimplifyToleranceMm = (double)_nudSimplify.Value,
        Optimize = _chkOptimize.Checked,
        Layers = (int)_nudLayers.Value,
        LayerHeightMm = (double)_nudLayerHeight.Value
    };
    private static string BuildGCode(List<List<Point2D>> paths, int layers, double height)
    {
        var b = new StringBuilder($"; Generated by GcodeViewer CFS\n; All Layers: {layers}\nG21\nG90\n");
        for (int z = 0; z < layers; z++)
        {
            b.AppendLine($"; LAYER {z + 1}/{layers}");
            b.AppendLine($"G1 Z{z * height:F3}");
            foreach (var source in paths)
            {
                var path = z % 2 == 0 ? source.AsEnumerable().Reverse().ToList() : source;
                if (path.Count < 2) continue;
                b.AppendLine($"G0 X{path[0].X:F3} Y{path[0].Y:F3}");
                foreach (var p in path.Skip(1))
                    b.AppendLine($"G1 X{p.X:F3} Y{p.Y:F3} F600");
            }
        }
        b.Append("M2\n");
        return b.ToString();
    }
    private void BtnSave_Click(object? s, EventArgs e)
    {
        using var d = new SaveFileDialog { Filter = "G-code|*.gcode;*.nc|所有文件|*.*", FileName = _imageFileName + ".gcode" };
        if (d.ShowDialog(this) == DialogResult.OK) File.WriteAllText(d.FileName, _gcode, Encoding.UTF8);
    }
    private void ShowPathComparison()
    {
        if (_image == null) return;
        if (!_chkPlot.Checked)
        {
            _picture.Image = _image;
            _pathComparisonImage?.Dispose();
            _pathComparisonImage = null;
            return;
        }

        var preview = BuildPathComparisonImage(_image, _paths,
            Math.Max(720, _picture.ClientSize.Width),
            Math.Max(420, _picture.ClientSize.Height));
        var previous = _pathComparisonImage;
        _pathComparisonImage = preview;
        _picture.Image = preview;
        _picture.Visible = true;
        previous?.Dispose();
    }

    private static Bitmap BuildPathComparisonImage(Bitmap source,
        IReadOnlyList<List<Point2D>> paths, int width, int height)
    {
        var bitmap = new Bitmap(width, height);
        using var graphics = Graphics.FromImage(bitmap);
        graphics.Clear(Color.FromArgb(242, 244, 247));
        graphics.SmoothingMode = SmoothingMode.AntiAlias;
        graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
        graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;

        const int outerPadding = 14;
        const int titleHeight = 34;
        const int gap = 14;
        int panelWidth = (width - outerPadding * 2 - gap) / 2;
        var leftPanel = new Rectangle(outerPadding, titleHeight, panelWidth,
            Math.Max(20, height - titleHeight - outerPadding));
        var rightPanel = new Rectangle(leftPanel.Right + gap, titleHeight,
            panelWidth, leftPanel.Height);

        using var titleFont = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
        using var detailFont = new Font("Microsoft YaHei UI", 8.5F);
        using var borderPen = new Pen(Color.FromArgb(185, 190, 198));
        using var panelBrush = new SolidBrush(Color.White);
        using var titleBrush = new SolidBrush(Color.FromArgb(38, 45, 55));
        using var detailBrush = new SolidBrush(Color.FromArgb(92, 100, 112));

        graphics.DrawString("原始图片", titleFont, titleBrush, leftPanel.Left, 8);
        graphics.DrawString($"生成路径  ·  {paths.Count} 条 / {paths.Sum(p => p.Count)} 点",
            titleFont, titleBrush, rightPanel.Left, 8);
        graphics.FillRectangle(panelBrush, leftPanel);
        graphics.FillRectangle(panelBrush, rightPanel);
        graphics.DrawRectangle(borderPen, leftPanel);
        graphics.DrawRectangle(borderPen, rightPanel);

        DrawImageFitted(graphics, source, Rectangle.Inflate(leftPanel, -10, -10));
        DrawPathsFitted(graphics, paths, Rectangle.Inflate(rightPanel, -16, -16));
        graphics.DrawString($"{source.Width} × {source.Height} px", detailFont,
            detailBrush, leftPanel.Left + 8, leftPanel.Bottom - 24);
        return bitmap;
    }

    private static void DrawImageFitted(Graphics graphics, Image image, Rectangle bounds)
    {
        if (bounds.Width <= 0 || bounds.Height <= 0) return;
        double scale = Math.Min((double)bounds.Width / image.Width,
            (double)bounds.Height / image.Height);
        int drawWidth = Math.Max(1, (int)Math.Round(image.Width * scale));
        int drawHeight = Math.Max(1, (int)Math.Round(image.Height * scale));
        var target = new Rectangle(
            bounds.Left + (bounds.Width - drawWidth) / 2,
            bounds.Top + (bounds.Height - drawHeight) / 2,
            drawWidth, drawHeight);
        graphics.DrawImage(image, target);
    }

    private static void DrawPathsFitted(Graphics graphics,
        IReadOnlyList<List<Point2D>> paths, Rectangle bounds)
    {
        var points = paths.SelectMany(path => path).ToList();
        if (points.Count < 2 || bounds.Width <= 0 || bounds.Height <= 0) return;

        double minX = points.Min(p => p.X);
        double maxX = points.Max(p => p.X);
        double minY = points.Min(p => p.Y);
        double maxY = points.Max(p => p.Y);
        double pathWidth = Math.Max(1e-9, maxX - minX);
        double pathHeight = Math.Max(1e-9, maxY - minY);
        double scale = Math.Min(bounds.Width / pathWidth, bounds.Height / pathHeight);
        double offsetX = bounds.Left + (bounds.Width - pathWidth * scale) / 2;
        double offsetY = bounds.Top + (bounds.Height - pathHeight * scale) / 2;
        Color[] colors =
        {
            Color.FromArgb(28, 91, 170), Color.FromArgb(205, 73, 68),
            Color.FromArgb(45, 142, 91), Color.FromArgb(157, 83, 171)
        };

        for (int index = 0; index < paths.Count; index++)
        {
            var path = paths[index];
            if (path.Count < 2) continue;
            var screenPoints = path.Select(p => new PointF(
                (float)(offsetX + (p.X - minX) * scale),
                (float)(offsetY + (p.Y - minY) * scale))).ToArray();
            using var pen = new Pen(colors[index % colors.Length], 1.5F)
            {
                LineJoin = LineJoin.Round,
                StartCap = LineCap.Round,
                EndCap = LineCap.Round
            };
            graphics.DrawLines(pen, screenPoints);
        }
    }

    private void Canvas_Paint(object? sender, PaintEventArgs e)
    {
        if (!_picture.Visible && _chkPlot.Checked && _paths.Count > 0)
            DrawPathsFitted(e.Graphics, _paths,
                Rectangle.Inflate(_canvas.ClientRectangle, -10, -10));
    }

    protected override void OnFormClosed(FormClosedEventArgs e)
    {
        _picture.Image = null;
        _pathComparisonImage?.Dispose();
        _image?.Dispose();
        base.OnFormClosed(e);
    }
}
